<template>
	<section class="features" id="features">
		<h2 class="section-title">Layout Features</h2>

		<div class="content" v-if="hasRequiredFeatures">
			<h3>Required layout features</h3>
			<p>
				These are always turned on by the system that renders the font.
				You can’t turn them off — in fact, you're not supposed to!
				Required layout features may be applicable only to certain
				language scripts or specific languages, or in certain writing
				modes.
			</p>
			<ul class="required-features">
				<li
					v-for="feature in requiredFeatures"
					:key="`reqfeat_${feature.tag}`"
				>
					<span class="opentype-label">{{ feature.tag }}</span>
					{{ feature.name }}
				</li>
			</ul>
		</div>
		<div class="content" v-if="hasOptionalFeatures">
			<h3>Optional layout features</h3>
			<p>
				Some are turned on by default, but can be turned off. Others are
				turned off by default, but can be turned on.
			</p>

			<div
				v-for="feature in optionalFeatures"
				:key="`optfeat_${feature.tag}`"
				class="feature-demo"
			>
				<div class="feature-control">
					<span class="opentype-label">{{ feature.tag }}</span>
					{{ feature.name }}
					<span
						class="state"
						:class="feature.state === 'on' ? 'on' : 'off'"
					>
						<strong v-if="feature.state === 'on'">On</strong>
						<strong v-else>Off</strong>
						by default
					</span>
					<label class="flip-state">
						<input
							type="checkbox"
							@change="flipState(feature.tag)"
							:disabled="!featureChars[feature.tag]"
							checked
						/><span>Show</span>
					</label>
				</div>

				<template v-if="isValidFeature(feature)">
					<template
						v-for="(lookup, index) in featureChars[feature.tag][
							'lookups'
						]"
					>
						<div
							v-if="lookup['type'] === 3"
							:style="getFeatureStyle(feature.tag)"
							:data-type="lookup['typeName']"
							:key="`lookup_3_${feature.tag}_${index}`"
							class="chars"
							contenteditable
							spellcheck="false"
						>
							<template v-for="(char, index) in lookup['input']">
								<span
									v-for="n in lookup['alternateCount'][index]"
									:key="`type3_${char}_${n}`"
									:style="getFeatureStyle(feature.tag, n)"
								>
									{{ char }}
								</span>
							</template>
						</div>

						<template v-else-if="lookup['type'] === 6"></template>

						<div
							v-else
							:style="getFeatureStyle(feature.tag)"
							:data-type="lookup['typeName']"
							:key="`lookup_6_${feature.tag}_${index}`"
							class="chars"
							contenteditable
							spellcheck="false"
						>
							{{ lookup["input"].join(" ") }}
						</div>
					</template>

					<template
						v-if="
							featureChars[feature.tag]['summary'][
								'summarizedCombinations'
							].length
						"
					>
						<div
							v-if="
								featureChars[feature.tag]['summary'][
									'allBacktracks'
								].length
							"
							:style="getFeatureStyle(feature.tag)"
							:key="`btsummary_${feature.tag}_{index}`"
							data-type="Chained Contexts Substitution"
							data-summary="Summarized backtrack"
							class="chars summarized"
							contenteditable
							spellcheck="false"
						>
							{{
								featureChars[feature.tag]["summary"][
									"allBacktracks"
								].join(" ")
							}}
						</div>

						<div
							:style="getFeatureStyle(feature.tag)"
							:key="`insummary_${feature.tag}_{index}`"
							data-summary="Summarized input"
							class="chars summarized"
							contenteditable
							spellcheck="false"
						>
							{{
								featureChars[feature.tag]["summary"][
									"allInputs"
								].join(" ")
							}}
						</div>

						<div
							v-if="
								featureChars[feature.tag]['summary'][
									'allLookaheads'
								].length
							"
							:style="getFeatureStyle(feature.tag)"
							:key="`lasummary_${feature.tag}_{index}`"
							data-summary="Summarized lookahead"
							class="chars summarized"
							contenteditable
							spellcheck="false"
						>
							{{
								featureChars[feature.tag]["summary"][
									"allLookaheads"
								].join(" ")
							}}
						</div>

						<div
							:style="getFeatureStyle(feature.tag)"
							:key="`combsummary_${feature.tag}_{index}`"
							data-summary="Randomly generated sample of possible combinations"
							class="chars summarized"
							contenteditable
							spellcheck="false"
						>
							{{
								featureChars[feature.tag]["summary"][
									"summarizedCombinations"
								].join(" ")
							}}
						</div>
					</template>
				</template>
				<div
					v-else
					class="no-chars"
					:style="getFeatureStyle(feature.tag)"
				>
					This feature appears to only modify glyphs generated by
					other features.
				</div>
			</div>
		</div>
	</section>
</template>

<script>
export default {
	props: ["font"],
	data() {
		return {
			currentStates: [],
			hasOptionalFeatures:
				this.font.features.filter((f) => f.state !== "fixed").length >
				0,
			hasRequiredFeatures:
				this.font.features.filter((f) => f.state === "fixed").length >
				0,
			featureChars: this.getFeatureChars(),
		};
	},
	computed: {
		optionalFeatures() {
			return this.font.features.filter((f) => f.state !== "fixed");
		},
		requiredFeatures() {
			return this.font.features.filter((f) => f.state === "fixed");
		},
	},
	methods: {
		getFeatureChars() {
			// Try to return the "best" layout features
			if (
				"DFLT" in this.font.featureChars &&
				"dflt" in this.font.featureChars["DFLT"]
			) {
				return this.font.featureChars["DFLT"]["dflt"];
			} else if (
				"latn" in this.font.featureChars &&
				"dflt" in this.font.featureChars["latn"]
			) {
				return this.font.featureChars["latn"]["dflt"];
			} else if (Object.keys(this.font.featureChars).length > 0) {
				// If all else fails, return first
				const first = Object.keys(this.font.featureChars)[0];
				return Object.values(this.font.featureChars[first])[0];
			} else {
				return {};
			}
		},
		flipState(feature) {
			this.currentStates[feature] = 1 - this.currentStates[feature];
		},
		isValidFeature(feature) {
			return (
				this.featureChars[feature.tag] &&
				this.featureChars[feature.tag]["lookups"].length &&
				this.featureChars[feature.tag]["lookups"][0]["input"].length
			);
		},
		// Use onState for features that take a specific number
		// instead of just 0 or 1.
		getFeatureStyle: function (feature, onState = 1) {
			const offState = 0;
			let state;
			if (this.currentStates[feature] !== undefined) {
				// CSS state exists, use it
				state = this.currentStates[feature];
			} else {
				// No CSS state yet, create one based off default state
				this.currentStates[feature] = 1;
				state = 1;
			}
			return `font-feature-settings:"${feature}" ${
				state ? onState : offState
			};`;
		},
	},
};
</script>

<style scoped>
.features p {
	margin: 1rem 0;
}

.features .content + .content {
	margin-top: 4rem;
}

.required-features li {
	margin-bottom: var(--small-margin);
}

.feature-demo + .feature-demo {
	margin-top: 1rem;
}

.state {
	margin-left: auto;
	margin-right: 0.5em;
	color: var(--yellow);
}

.state.on {
	color: var(--green);
}

.flip-state [disabled] + span {
	color: var(--unlighterer-grey);
}

.required-features li,
.feature-control {
	display: flex;
	align-items: center;
}

.chars {
	position: relative;
	font-family: var(--font-stack);
	font-size: 1.5rem;
	background: var(--light-grey);
	padding: 1.5rem 0.5rem 0.5rem 0.5rem;
	margin-top: var(--small-margin);
	overflow: hidden;
}

.chars[data-type]::before {
	content: attr(data-type);
	position: absolute;
	top: var(--small-margin);
	left: var(--small-margin);
	background: var(--unlighter-grey);
	font-feature-settings: normal !important;
	font-family: var(--system-font-stack);
	font-size: 0.75rem;
	padding: 0 4px 2px 4px;
	border-radius: 2px;
}

.chars.summarized::after {
	content: attr(data-summary);
	position: absolute;
	top: var(--small-margin);
	right: var(--small-margin);
	background: var(--unlighter-grey);
	font-feature-settings: normal !important;
	font-family: var(--system-font-stack);
	font-size: 0.75rem;
	padding: 0 4px 2px 4px;
	border-radius: 2px;
}

.no-chars {
	font-feature-settings: normal !important;
	font-family: var(--system-font-stack);
	font-style: italic;
	color: var(--unlighterer-grey);
	background: var(--light-grey);
	padding: 0.5rem;
	margin-top: var(--small-margin);
	overflow: hidden;
}

/*

Committing this as I would like to preserve this
for when a user can toggle between a Type 6 summary
and the raw backtrack/input/lookahead

.backtrack::before {
	content: "Before";
	display: inline-block;

	background: var(--unlighter-grey);
	font-feature-settings: normal !important;
	font-family: var(--system-font-stack);
	font-size: 0.75rem;
	padding: 0 4px 2px 4px;
	border-radius: 2px;
}

.input::before {
	content: "Input";
	display: inline-block;

	background: var(--unlighter-grey);
	font-feature-settings: normal !important;
	font-family: var(--system-font-stack);
	font-size: 0.75rem;
	padding: 0 4px 2px 4px;
	border-radius: 2px;
}

.lookahead::before {
	content: "After";
	display: inline-block;

	background: var(--unlighter-grey);
	font-feature-settings: normal !important;
	font-family: var(--system-font-stack);
	font-size: 0.75rem;
	padding: 0 4px 2px 4px;
	border-radius: 2px;
}

.divider {
	height: 1em;
	background: white;
	margin: 1em -1em;
}

*/
</style>
